[target.armv7-unknown-linux-gnueabihf]
# Based on https://www.collabora.com/news-and-blog/blog/2020/06/23/cross-building-rust-gstreamer-plugins-for-the-raspberry-pi/
# but with `RUN apt-get install -y libdbus-1-dev:armhf` thrown in to get the dependency we need.
# This image has been pushed to dockerhub.
image = "ghcr.io/qwandor/cross-dbus-debian-buster-armv7:0.2.1-1"

# Once https://github.com/rust-embedded/cross/pull/446 gets somewhere, you
# will be able to use `context` and `dockerfile` to achieve the same result.
# When developing changes to the build container, it may be useful to do:
# cargo install --git=https://github.com/alsuren/cross --branch=docker-build-context
# and then comment out `image`, above and uncomment the following two lines:
# context = "./docker"
# dockerfile = "./docker/Dockerfile.debian-buster-armv7"

[target.arm-unknown-linux-gnueabi]
# image = "ghcr.io/qwandor/cross-dbus-debian-buster-armv6:TBD"

# context = "./docker"
# dockerfile = "./docker/Dockerfile.debian-buster-armv6"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/qwandor/cross-dbus-debian-buster-aarch64:0.2.1-1"

# context = "./docker"
# dockerfile = "./docker/Dockerfile.debian-buster-aarch64"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/qwandor/cross-dbus-debian-buster-x86_64:0.2.1-1"

# context = "./docker"
# dockerfile = "./docker/Dockerfile.debian-buster-x86_64"
