[package]
name = "publish-mqtt"
version = "0.1.0"
authors = ["David Laban <alsuren@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "1.4.0"
blurz = "0.4.0"
color-backtrace = "0.4.2"
futures = "*"
mijia = { path = "../mijia" }
pretty_env_logger = "0.4.0"
rumqttc = { git = "https://github.com/bytebeamio/rumqtt" }
rustls = "0.17"
rustls-native-certs = "0.3"
tokio = "0.2.22"
