name: Lint

on:
  push:
    branches: [master]
  pull_request:

env:
  dbus-codegen-version: 0.9.0

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  generated:
    name: Check that generated files haven't been modified
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache dbus-codegen-rust
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/dbus-codegen-rust
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-cargo-bin-${{ env.dbus-codegen-version }}

      - name: Install dbus-codegen dependencies
        run: sudo apt-get install libdbus-1-dev

      - name: Install dbus-codegen
        run: cargo install dbus-codegen --version ${{ env.dbus-codegen-version }}

      - name: Rebuild generated files
        run: INTROSPECT=0 ./bluez-generated/introspect.sh

      - name: Check for differences
        run: git diff --exit-code
